---
title: "Capstone Project: Analysis of Media Coverage and Sentiment Around Endometriosis with the GDELT API"
author: "Salome Schwegler"
format: pdf
editor: visual
---

## LLM disclosure

## Introduction

Endometriosis is a chronic inflammatory illness in which tissue resembling the endometrial lining of the uterus grows elsewhere, causing severe pain and a wide range of symptoms (Culley et al. 2013). Despite affecting an estimated 190 million people worldwide, endometriosis remains significantly underdiagnosed, with patients waiting an average of seven to ten years before receiving an accurate diagnosis (Shafrir et al. 2018). The estimated number of unreported cases is assumed to be much greater. The diagnostic delay can be attributed to structural shortcomings within healthcare systems and research, as well as to a broader lack of cultural acceptance of the illness (Armour et al. 2020). Both structural issues and the degree of societal acceptance are sustained and reflected by media coverage.

This capstone project, conducted within the data mining class, examines global and multilingual news coverage of endometriosis with the use of the Global Database of Events, Language, and Tone (GDELT Project). The GDELT Project is the largest open database of the human society that has ever been created. The database aims to display all data about our society and to foster interconnectivity across the globe. This is achieved by capturing and representing media coverage from almost every corner of the world. The database is updated daily, while the real-time datasets are updated every 15 minutes.

Analysing news coverage of endometriosis contributes to a better understanding of how the condition is perceived in society and the extent to which new scientific developments, such as advances in identifying the root causes of the illness or emerging treatment options and new medications, are reflected in public discourse.

Truthfully this project aimed to examine the content of news articles and the specific topics covered in articles about endometriosis. This included, for instance, whether articles provide general explanations of the condition, document personal live experiences of patients, report on new medications and treatments in light of recent scientific and academic progress or serve as practical guides for those affected. Just to name a few expected topics. However, this goal proved unfeasible give the scope of the project, the limitations of the API and legal constraints. The GDELT API does not permit the extraction of full article text, partly because the articles originate from a wide range of news organisations and portals, the majority of which operate behind paywalls. It was therefore only possible to retrieve basic metadata via the API, such as the URL, date, country and language of each article. While web scraping could theoretically have enabled full text extraction, given that article URLSs were correctly extracted and hence available, this approach was however deliberately avoided. As discussed repeatedly in class, web scraping requires extreme caution and should be avoided where possible due to legal concerns. It should also be noted that the GDELT API only allows articles extraction for the preceding three months, which poses on additional limitation on the scope of this research. The research question were therefore revised iteratively to reflect what is empirically feasible within the constraints of the data source.

### Research question

Due to the limited scope of this project and the constraints of data accessibility through the GDELT Project API, two adapted research questions will guide the following analysis:  

**RQ1:** Which countries produce the greatest volume of news coverage about endometriosis?

**RQ2:** How has the average sentiment tone of endometriosis news coverage changed over the past four years?

## Data and Methodology

### Data source

All data for this project was retrieved from the GDELT Project. Its document version 2.0. GDELT is a real-time open data platform that monitors print, broadcast and web news media across the world in 152 languages. 65 languages are translated in real-time. It processes hundreds of thousands of articles per day and encodes information about “people, locations, organisations, themes, sources, emotions, counts, quotes, images and events” (<https://www.gdeltproject.org/>). For the purpose of this project two distinct query modes of the GDELT DOC API were used:

“Artlist”, which returns metadata of individual article and “TimelineTone”, which returns time-series sentiment data aggregated across all matching documents.

The API was accessed via HTTP GET request using the httr package in R. The endpoint used was <https://api.gdeltproject.org/api/v2/doc/doc>, with query parameters for the search term, mode, time range and output format. No API key is required to access GDELT, which is a big advantage. However the platform enforces rate limits on the frequency of the requests which is why Sys.sleep(6) and timeout(60) was integrated into the request.

The next section will elaborate on how data was accessed, preprocessed and analysed for both distinct query modes separately.

### Data access and API

The GDELT Project provides open access to its data through an API. An API is a standardised communication channel that allows to request data from one software system to another over the internet. In practical terms, a request is sent to the GDELT server in the form of a URL containing a set of parameters which specify i.e. the research keyword(s), the time range, query mode and the output format. The server then processes the request and returns the matching data which in this case is in JSON format. The JSON format can be parsed and converted into a dataframe in R. All requests were made using the httr package in R, which handles the HTTP GET requests. As mentioned above a pause of six seconds between calls was introduced to avoid being blocked by the server.

### Load libraries

The following R libraries need to be loaded (or installed):

```{r}
# load libraries ----------------------------------------------------------
library(tidyverse)
library(httr)
#library(rvest)
library(jsonlite)
library(lubridate)
```

### Article extraction (artlist mode)

#### Getting the data

#### Preprocessing the data

#### Analysis

### Sentiment score (TimelineTone mode)

#### Getting the data

#### Preprocessing the data

#### Analysis

## Conclusion and Limitations
